eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9100
  servlet:
    context-path: /cloud
spring:
  application:
    name: cloud
aliyun:
  oss:
    accessKeyId: LTAI4GGChi16cxpdKnZvb7po
    accessKeySecret: JH6oNNd1wjaxBcze8RcCZQJ0bsHeSy
    bucketName: ihuzhu-dev
    domain: https://ihuzhu-dev.oss-cn-beijing.aliyuncs.com/
    endpoint: oss-cn-beijing.aliyuncs.com
tencent:
  cloud:
    secretId: AKIDpOwEG26mY6NchVgD5h9M7ctu3x2tNvc6
    secretKey: FI6dDtJTMgphIldFbjOpzsZfZDZcQxEM
    token: ''
    region: ap-beijing
  lbs:
    key: SFVBZ-GLLKP-IYGDG-LRMQ4-NEL4Q-YBBWA
    secretKey: rw4XzZQYbLsRTupRTTq16W0yz1RZCCla
wx:
  miniapp:
    aesKey: ''
    appid: wxa340fb00f9f9cf97
    msgDataFormat: JSON
    secret: 6c4d7eba5ca749f6d07ed0a3ab4f442e
    token: ''