eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9100
  servlet:
    context-path: /cloud
spring:
  application:
    name: cloud
aliyun:
  oss:
    accessKeyId: 
    accessKeySecret: 
    bucketName: ihelp
    domain: 
    endpoint: 
tencent:
  cloud:
    secretId: 
    secretKey: 
    token: ''
    region: ap-beijing
  lbs:
    key: 
    secretKey: 
wx:
  miniapp:
    aesKey: ''
    appid: 
    msgDataFormat: JSON
    secret: 
    token: ''
