server:
  port: 9001
  servlet:
    context-path: /mp
spring:
  application:
    name: miniapp
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: full
  hystrix:
    enabled: false
