eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  redis:
    database: 1
    host: 49.232.166.172
    password: Test!234
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: Test!234
    url: jdbc:mysql://49.232.166.172:33060/ihuzhu?characterEncoding=UTF8&autoReconnect=true&useSSL=false
    username: root
logging:
  level:
    com:
      services:
        products:
          ihelp:
            dao:
              mapper: trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
base:
  ossDomain: https://ihelp.oss-cn-beijing.aliyuncs.com/
